### ISSUE TITLE
p20~p38の環境構築がうまくできません

### ISSUE THREAD

**Issue by yuki0629** [yuumi3/react_book#19]
MacでReactを学ぼうとしているのですが、hello_reactのフォルダを作り、全てのファイルをgitのソースを元に作成したにも関わらず、

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)
    at Object.runInThisContext (vm.js:319:10)
    at Module._compile (internal/modules/cjs/loader.js:685:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! hello_react@1.0.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hello_react@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

といったエラーがでます。

**Comment by yuumi3** [comment]
@yuki0629 さん、最新のnode, npmで試しましたが、こちらでは上手く動きました。 

-  **SyntaxError: Unexpected identifier** は予期せぬ識別しがあったというエラーです。設定ファイル webpack.config.js  に間違いがないか注意深く見直してもらえますか
- それから、エラーメッセージですが `npm start` コマンドの直後からコピー＆ペーストしてもらないでしょうか

試しに、webpack.config.js の4行目の **,** を削除して実行すると以下のようなエラーが発生しました。

```
$ npm start

> hello_react@1.0.0 start /Users/yy/tmp/react_code/hello2
> webpack-dev-server

/Users/yy/tmp/react_code/hello2/webpack.config.js:5
  output: {
  ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:83:7)
    at createScript (vm.js:267:10)

   ・・・以下省略・・・
```

**Comment by yuki0629** [comment]
返信ありがとうございます。
webpack.config.jsをもう一度削除して、ソースコード通りにコピーしたらうまく行きました。

**Comment by yuumi3** [comment]
良かったです  ^^)
