### ISSUE TITLE
コンパイル時にESLintでforEach文にエラーが出ます

### ISSUE THREAD

**Issue by Danna-jp** [yuumi3/react_book#22]
READE.MDのコミットのコメントにも書かせてもらいましたが

ERROR in ./src/index.js
Module build failed (from ./node_modules/eslint-loader/dist/cjs.js):
TypeError: Cannot read property 'forEach' of undefined
    at Linter.parseResults (C:\Users\Danna\Desktop\react-cource-projects\hello_react\node_modules\eslint-loader\dist\Linter.js:121:13)
    at Linter.printOutput (C:\Users\Danna\Desktop\react-cource-projects\hello_react\node_modules\eslint-loader\dist\Linter.js:85:26)
    at Object.loader (C:\Users\Danna\Desktop\react-cource-projects\hello_react\node_modules\eslint-loader\dist\index.js:26:10)
i ｢wdm｣: Failed to compile.

とコンパイルができません。以下にエラーが出るforEach文を載せておきます。

  parseResults({
    results
  }) {
    // add filename for each results so formatter can have relevant filename
    results.forEach(r => {
      // eslint-disable-next-line no-param-reassign
      r.filePath = this.loaderContext.resourcePath;
    });
    return results;
  }

**Comment by yuumi3** [comment]
@Danna-jp さん
エラーメッセージ
`TypeError: Cannot read property 'forEach' of undefined`
を読むと results の値が undefined のようです。

書籍のどのページのコードでエラーが出ているのでしょうか？
